<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Seadora.Customer.Application\Seadora.Customer.Application.csproj" />
    <ProjectReference Include="..\Seadora.Customer.Domain\Seadora.Customer.Domain.csproj" />
    <ProjectReference Include="..\..\Common\Seadora.Common\Seadora.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
